name : test-github-wf
on: [push]
jobs:
 check-node-version:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
    - run: npm install -g firebase
    - run: node --version
